### ISSUE TITLE
Completed items not removed from outline, re-added to todo.txt

### ISSUE THREAD

**Issue by david-a-d** [samuelsnyder/outline-todo.txt#3]
Hello Samuel

As above. The problem is there whether or not I choose to archive done items before syncing the outline.

**Comment by samuelsnyder** [comment]
did a major overhaul. let me know how it works for you now.

**Comment by david-a-d** [comment]
Thanks! I'll give it a go in a few days.

**Comment by david-a-d** [comment]
Hey! It seems to be working great. Thanks.
