### ISSUE TITLE
Unable to handle file paths with spaces?

### ISSUE THREAD

**Issue by bobpwei** [samuelsnyder/outline-todo.txt#6]
When the outline path is `~/My Dropbox/todo/foobar.ol.txt` i get the following:
```
> todo.sh outline edit foobar
No outline file corresponding to project foobar found.
```
but when the outline path is `~/Dropbox/todo/foobar.ol.txt` it successfully opens the file in the editor.

Are the file paths not being properly escaped?

**Comment by samuelsnyder** [comment]
Fixed
